---
- name: Check if override path is defined for customize_filesystem
  set_fact:
    custom_path: "{{ customize_node_filesystems | default( role_path + '/files/customize_filesystem' ) }}"

- name: Verify if {{ custom_path }}/master/worker is empty
  find:
    paths: "{{ custom_path }}/{{ item }}"
    recurse: yes
    follow: yes
  register: filesFound
  with_items:
    - "master"
    - "worker"
  delegate_to: localhost
  tags: customfs

- name: Modify Ignition Configs
  block:

  - name: Create OpenShift Ignition Configs
    shell: |
      /usr/local/bin/openshift-baremetal-install --dir {{ dir }} create ignition-configs

  - name: Copy Ignition Config Files
    copy:
      src: "{{ dir }}/{{ item }}.ign"
      dest: "{{ dir }}/{{ item }}.ign.orig"
      remote_src: yes
    with_items:
      - "master"
      - "worker"

  - name: Copy customize_filesystem to tempdir
    copy:
      src: "{{ custom_path }}/"
      dest: "{{ tempdir }}/customize_filesystem"
      force: yes

  - name: Cleanup Any .gitkeep Files in the Fake Root
    file:
      path: "{{ tempdir }}/customize_filesystem/{{ item }}/.gitkeep"
      state: absent
      follow: yes
    with_items:
      - "master"
      - "worker"
    become: true

  - name: "Find jinja2 Templates"
    find:
      patterns: "*.j2"
      paths: "{{ tempdir }}/customize_filesystem"
      recurse: yes
    register: customize_filesystem_template_search

  - name: "Find jinja2 Templates Meant For Destination Nodes (.j2.nondeploy)"
    find:
      patterns: "*.j2.nondeploy"
      paths: "{{ tempdir }}/customize_filesystem"
      recurse: yes
    register: customize_filesystem_static_template_search

  - name: "Extract Previous Searches Into Targeted Facts"
    set_fact:
      customize_filesystem_template_files: "{{ customize_filesystem_template_search | json_query('files[].path') }}"
      customize_filesystem_static_template_files: "{{ customize_filesystem_static_template_search | json_query('files[].path') }}"

  - name: "Render Templates To Their Final Destinations"
    template:
      src: "{{ item }}"
      dest: "{{ item | regex_replace('\\.j2$', '') }}"
    with_items: "{{ customize_filesystem_template_files }}"

  - name: "Remove customize_filesystem Deployment Templates"
    file:
      state: absent
      path: "{{ item }}"
    with_items: "{{ customize_filesystem_template_files }}"

  - name: "Create Final .j2 Files From .j2.nondeploy Files"
    copy:
      src: "{{ item }}"
      dest: "{{ item | regex_replace('\\.j2\\.nondeploy$', '.j2') }}"
    with_items: "{{ customize_filesystem_static_template_files }}"

  - name: "Remove Original .j2.nondeploy Files"
    file:
       state: absent
       path: "{{ item }}"
    with_items: "{{ customize_filesystem_static_template_files }}"

  - name: Augment Ignition Config Files
    script: |
      filetranspile-1.1.1.py -i {{ dir }}/{{ item }}.ign.orig -f {{ tempdir }}/customize_filesystem/{{ item }} -o {{ dir }}/{{ item }}.ign
    args:
      executable: python3
    with_items:
      - "master"
      - "worker"
    become: true

  - name: Create backup of ignition config files
    copy:
      src: "{{ dir }}/{{ item }}.ign"
      dest: "{{ dir }}/{{ item }}.ign.bkup"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'
      remote_src: yes
    with_items:
      - "master"
      - "worker"

  when: (filesFound | json_query('results[*].matched') | sum) > 0
  tags: customfs
